import { Inter } from 'next/font/google';

// eslint-disable-next-line import/order
import './globals.css';

import Header from '@/components/Header';
import AuthContext from '@/context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${inter.className}`}>
                <AuthContext>
                    <main className="mx-auto max-w-[1200px]">
                        <Header />
                        {children}
                    </main>
                </AuthContext>
            </body>
        </html>
    );
}
